# Several Examples for Detecting Outliers

## Elliptic Envelope

In [1]:
import numpy as np
from sklearn.covariance import EllipticEnvelope

# Create a sample normal distribution
X = np.random.normal(loc=5, scale=2, size=50).reshape(-1, 1)

# Fit the estimator
ee = EllipticEnvelope(random_state=0)
_ = ee.fit(X)

# Test
test = np.array([6, 8, 20, 4, 5, 6, 10, 13]).reshape(-1, 1)

# predict returns 1 for an inlier and -1 for an outlier
ee.predict(test)

array([ 1, -1, -1,  1,  1,  1, -1, -1])

## Isolation Forest

In [5]:
import numpy as np
from sklearn.ensemble import IsolationForest

X = np.array([-1.1, 0.3, 0.5, 100]).reshape(-1, 1)

clf = IsolationForest(random_state=0).fit(X)

clf.predict([[0.1], [0], [90]])
# array([ 1,  1, -1])

array([ 1,  1, -1])